# Generated by Django 5.2 on 2025-05-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='categoria',
            field=models.CharField(choices=[('general', 'General'), ('tecnologia', 'Tecnología'), ('spiderman', 'Spider-Man')], default='general', max_length=20),
        ),
    ]
