# Generated by Django 5.2 on 2025-05-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpidermanVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.TextField()),
                ('nombre', models.TextField()),
                ('datos', models.TextField()),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
